### ISSUE TITLE
pt_BR translation

### ISSUE THREAD

**Issue by EPuncker** [lesterchan/wp-postviews#25]
I've translated the plugin into Brazilian portuguese, I do not know if this is the right place to post since I'm kinda new here, I don't know how to attach a file either so I've uploaded a zip file containing the wp-postviews-pt_BR.mo and wp-postviews-pt_BR.po into depositfiles

[http://depositfiles.com/files/wsgasawid]

**Comment by lesterchan** [comment]
I am movign towards using translate.wordpress.org, https://translate.wordpress.org/projects/wp-plugins/wp-postviews https://translate.wordpress.org/locale/pt-br/default/wp-plugins/wp-postviews

**Comment by EPuncker** [comment]
so I need to translate everything again? 😅

**Comment by lesterchan** [comment]
Unfortunately yes :(

**Comment by EPuncker** [comment]
okay but which one should I focus on, trunk or stable?

**Comment by lesterchan** [comment]
trunk
