### ISSUE TITLE
Jetpack WP Stats Integration

### ISSUE THREAD

**Issue by VR51** [lesterchan/wp-postviews#27]
I can see in the change log that you mention a fix for WP Stats integration. I've installed WP Postviews into a website that is integrated with Jetpack Stats (which I assume is the WP Stats mentioned in the fix). The view counts shown by the [views] shortcode do not appear to reflect historical WP Stats data. Have I misunderstood the plugin's features or do I need to alter a setting?

**Comment by lesterchan** [comment]
The WP-Stats is my own plugin not Jetpack

**Comment by VR51** [comment]
Got it. Thank you
