### ISSUE TITLE
Is Not Updating 

### ISSUE THREAD

**Issue by freddiehdxd** [lesterchan/wp-postviews#31]
on my site the views are not updating in live 
the update post view sometimes it not displaying the right amount of view

**Comment by lesterchan** [comment]
If you are using caching plugin this will happen. Because the output is being cached.

**Comment by freddiehdxd** [comment]
so how to fix it with a cache plugin ?

**Comment by lesterchan** [comment]
Sorry you can't, it is not designed to work with caching plugin. The views will still count, just that the views will not be updated till the template cache of your caching plugin expires.

**Comment by freddiehdxd** [comment]
oh ok thanks
