### ISSUE TITLE
Create a Draft based on an existent Post/Page

### ISSUE THREAD

**Issue by sobreira** [lesterchan/wp-postviews#32]
Hi, first of all, thanks for this plugin.
It´s amazing and works very fine.
I realized, recently (probably since all), that when I copy an existent post as a draft to save time in edition, the came with the same views as the original one.

Did you already have the same experience?

Thanks

Edson Sobreira

![image](https://cloud.githubusercontent.com/assets/5200448/25409543/c3296ecc-29e8-11e7-9cf6-08b5345cf9a3.png)

**Comment by lesterchan** [comment]
Are u using a plugin for it to copy the post? If so I am guessing it duplicates the views meta field as well.
