### ISSUE TITLE
Backup view counts before reinstall WordPress

### ISSUE THREAD

**Issue by hasancse91** [lesterchan/wp-postviews#33]
Sir,
First of all thanks for the plugin.
I need to reinstall my WP blog site. Is any option to store and restore view counts? I took backup my site without plugin backup. just took post, page and database backup. So I'm scared about loss the view counts. Can you give me any suggestion please?

**Comment by lesterchan** [comment]
The view count are stored in the wp_postmeta table, so if the wp_postmeta is backed up, the view will be there.

**Comment by hasancse91** [comment]
Thank you sir for your amazing quick response. Thanks a lot.
You may close the issue now :+1:
