### ISSUE TITLE
wordpress 5.0.1 warning

### ISSUE THREAD

**Issue by qazwsdc** [lesterchan/wp-postviews#37]
When I install 1.7.6 on wordpress 5.0.1.There are two line Warning message in the admin's article page:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'sort_postviews_column ' not found or invalid function name in /www/wwwroot/wordpress/wp-includes/class-wp-hook.php on line 286

Warning: Invalid argument supplied for foreach() in /www/wwwroot/wordpress/wp-admin/includes/class-wp-list-table.php on line 967

And when I disable the wp-postviews , this warning message disappear

**Comment by lesterchan** [comment]
Thanks fixed in  
https://github.com/lesterchan/wp-postviews/commit/f68967faef49fa637aaa5dd67a495b6bafef428e. There is an additional space.

Thanks for reporting.
