### ISSUE TITLE
post view not showing

### ISSUE THREAD

**Issue by amirhrezf** [lesterchan/wp-postviews#38]
Hi
After updating your plugin to last version when i want to see all my posts i get this error
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function ‘sort_postviews_column ‘ not found or invalid function name in /home1/sourcekh/public_html/learn/wp-includes/class-wp-hook.php on line 286
please help fast

**Comment by lesterchan** [comment]
Please see https://github.com/lesterchan/wp-postviews/issues/37
