### ISSUE TITLE
Why "Views" Column in back-end is not sortable ?

### ISSUE THREAD

**Issue by Devlop-er** [lesterchan/wp-postviews#42]
I don't have the options to sort the views columns on my custom post type.
Should I do something special to enabled it ?

I found the sort_postviews_column function but can't get it working.

Thanks for your help

**Comment by lesterchan** [comment]
`You will need to add add_filter( 'manage_edit-<CUSTOM_POST_TYPE_sortable_columns', 'sort_postviews_column' );`, see https://codex.wordpress.org/Plugin_API/Filter_Reference/manage_$post_type_sortable_columns

**Comment by Devlop-er** [comment]
Thanks =)
