### ISSUE TITLE
FR - Use vanilla JS (not jQuery) loaded in footer

### ISSUE THREAD

**Issue by JiveDig** [lesterchan/wp-postviews#49]
This plugin seems useful, thanks! However, I can't use it because we don't want jQuery loading on our sites. I'm just making an official feature request if you could switch to `fetch` in JS instead of `ajax` in jQuery :)

**Comment by JiveDig** [comment]
PR submitted above. Let me know what you think!

**Comment by lesterchan** [comment]
Looks ok, can I assume you tested it. I am not using cache on my site, so I will not be testing it anytime soon.

**Comment by JiveDig** [comment]
Definitely works. I'm not super advanced with JS or Ajax calls, but I've done it a few times and this was pretty straightforward. I'm not sure what the cache !1 part was for but I left it in there.

**Comment by lesterchan** [comment]
false = !1 when it is minify :D

**Comment by JiveDig** [comment]
@lesterchan I'm hoping to run this on a live site soon. Do you plan to release an update with this and the other PR that had the bots update in the near future? Otherwise I may run the latest branch just to get some pageviews stored before we need them in our queries.

**Comment by lesterchan** [comment]
I don't think I will be releasing an update anytime soon. Feel free to use the latest master branch for now =)

**Comment by lesterchan** [comment]
https://github.com/lesterchan/wp-postviews/commit/3cd09cd654026fc5c12e7307733a354fa11f33ec
